from __future__ import annotations

from fms.core.config import Settings, settings
from fms.core.database import Base, async_session_factory, engine, get_db, get_db_context
from fms.core.dependencies import get_current_user, get_idempotency_key, require_role
from fms.core.enums import (
    BookingItemStatus,
    BookingStatus,
    CabinClass,
    FareType,
    FlightStatus,
    HoldStatus,
    LoyaltyTier,
    RefundStatus,
    RefundType,
    UserRole,
    WaitlistStatus,
)
from fms.core.exceptions import (
    ConflictError,
    FMSException,
    ForbiddenError,
    NotFoundError,
    OptimisticLockError,
    UnauthorizedError,
    ValidationError,
    fms_exception_handler,
)
from fms.core.policy import (
    AUTO_APPROVED_ACTIONS,
    CUTOFF_MINUTES,
    FLEXIBLE_FARE_MULTIPLIER,
    MANUAL_APPROVAL_ACTIONS,
    MAX_OPTIMISTIC_LOCK_RETRIES,
    SCHEDULE_CHANGE_OVERRIDE_HOURS,
    TIER_WEIGHT,
)
from fms.core.security import (
    create_access_token,
    create_refresh_token,
    decode_token,
    get_token_expiry,
    hash_password,
    verify_password,
)

__all__ = [
    "Settings",
    "settings",
    "Base",
    "engine",
    "async_session_factory",
    "get_db",
    "get_db_context",
    "get_current_user",
    "require_role",
    "get_idempotency_key",
    "UserRole",
    "LoyaltyTier",
    "CabinClass",
    "FareType",
    "FlightStatus",
    "HoldStatus",
    "BookingStatus",
    "BookingItemStatus",
    "WaitlistStatus",
    "RefundType",
    "RefundStatus",
    "FMSException",
    "NotFoundError",
    "ConflictError",
    "ValidationError",
    "UnauthorizedError",
    "ForbiddenError",
    "OptimisticLockError",
    "fms_exception_handler",
    "AUTO_APPROVED_ACTIONS",
    "MANUAL_APPROVAL_ACTIONS",
    "FLEXIBLE_FARE_MULTIPLIER",
    "SCHEDULE_CHANGE_OVERRIDE_HOURS",
    "MAX_OPTIMISTIC_LOCK_RETRIES",
    "CUTOFF_MINUTES",
    "TIER_WEIGHT",
    "hash_password",
    "verify_password",
    "create_access_token",
    "create_refresh_token",
    "decode_token",
    "get_token_expiry",
]