"""initial migration

Revision ID: e3113c01cbdd
Revises: 
Create Date: 2026-09-13 09:58:19.626417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e3113c01cbdd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('CUSTOMER', 'OPS_AGENT', 'SUPER_ADMIN', name='user_role_enum', create_constraint=True), nullable=False),
    sa.Column('loyalty_tier', sa.Enum('NONE', 'SILVER', 'GOLD', 'PLATINUM', name='loyalty_tier_enum', create_constraint=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('entity_type', sa.Text(), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('before_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_actor_created', 'audit_logs', ['actor_id', 'created_at'], unique=False)
    op.create_index('ix_audit_entity', 'audit_logs', ['entity_type', 'entity_id'], unique=False)
    op.create_table('bookings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('booking_reference', sa.String(length=20), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('CONFIRMED', 'PARTIALLY_CANCELLED', 'CANCELLED', name='booking_status_enum', create_constraint=True), nullable=False),
    sa.Column('total_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('payment_status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bookings_booking_reference'), 'bookings', ['booking_reference'], unique=True)
    op.create_table('flights',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('flight_number', sa.String(length=50), nullable=False),
    sa.Column('origin', sa.String(length=100), nullable=False),
    sa.Column('destination', sa.String(length=100), nullable=False),
    sa.Column('departure_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('arrival_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('SCHEDULED', 'DELAYED', 'CANCELLED', 'COMPLETED', name='flight_status_enum', create_constraint=True), nullable=False),
    sa.Column('total_seats', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('original_departure_datetime', sa.DateTime(timezone=True), nullable=True),
    sa.Column('original_arrival_datetime', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delay_reason', sa.String(length=500), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('arrival_datetime > departure_datetime', name='ck_flight_arrival_after_departure'),
    sa.CheckConstraint('total_seats > 0', name='ck_flight_total_seats_positive'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_flight_unique_per_day', 'flights', ['flight_number', 'origin', 'destination', sa.text("date_trunc('day', departure_datetime AT TIME ZONE 'UTC')")], unique=True)
    op.create_index(op.f('ix_flights_flight_number'), 'flights', ['flight_number'], unique=False)
    op.create_table('seat_classes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('flight_id', sa.UUID(), nullable=False),
    sa.Column('cabin_class', sa.Enum('ECONOMY', 'BUSINESS', 'FIRST', name='cabin_class_enum', create_constraint=True), nullable=False),
    sa.Column('total_seats', sa.Integer(), nullable=False),
    sa.Column('available_seats', sa.Integer(), nullable=False),
    sa.Column('overbooking_buffer', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.CheckConstraint('available_seats >= 0', name='ck_seat_class_available_seats_nonneg'),
    sa.CheckConstraint('overbooking_buffer >= 0', name='ck_seat_class_overbooking_buffer_nonneg'),
    sa.CheckConstraint('total_seats >= 0', name='ck_seat_class_total_seats_nonneg'),
    sa.ForeignKeyConstraint(['flight_id'], ['flights.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_seat_class_flight_cabin', 'seat_classes', ['flight_id', 'cabin_class'], unique=True)
    op.create_table('fares',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('seat_class_id', sa.UUID(), nullable=False),
    sa.Column('fare_type', sa.Enum('BASIC', 'FLEXIBLE', name='fare_type_enum', create_constraint=True), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('refundable', sa.Boolean(), nullable=False),
    sa.Column('change_allowed', sa.Boolean(), nullable=False),
    sa.Column('seat_choice_allowed', sa.Boolean(), nullable=False),
    sa.CheckConstraint('price > 0', name='ck_fare_price_positive'),
    sa.ForeignKeyConstraint(['seat_class_id'], ['seat_classes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_fare_seat_class_fare_type', 'fares', ['seat_class_id', 'fare_type'], unique=True)
    op.create_table('waitlist_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('flight_id', sa.UUID(), nullable=False),
    sa.Column('seat_class_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('WAITING', 'PROMOTED', 'EXPIRED', 'CANCELLED', name='waitlist_status_enum', create_constraint=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('quantity > 0', name='ck_waitlist_quantity_positive'),
    sa.ForeignKeyConstraint(['flight_id'], ['flights.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['seat_class_id'], ['seat_classes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_waitlist_flight_class_status', 'waitlist_entries', ['flight_id', 'seat_class_id', 'status'], unique=False)
    op.create_table('booking_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('flight_id', sa.UUID(), nullable=False),
    sa.Column('fare_id', sa.UUID(), nullable=False),
    sa.Column('leg_number', sa.Integer(), nullable=False),
    sa.Column('passenger_name', sa.String(length=255), nullable=False),
    sa.Column('seat_number', sa.String(length=20), nullable=True),
    sa.Column('status', sa.Enum('CONFIRMED', 'CANCELLED', name='booking_item_status_enum', create_constraint=True), nullable=False),
    sa.Column('price_paid', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('schedule_change_override', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['fare_id'], ['fares.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['flight_id'], ['flights.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('seat_holds',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('fare_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('locked_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'EXPIRED', 'CONVERTED', 'RELEASED', name='hold_status_enum', create_constraint=True), nullable=False),
    sa.Column('group_key', sa.UUID(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('quantity > 0', name='ck_seat_hold_quantity_positive'),
    sa.ForeignKeyConstraint(['fare_id'], ['fares.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_seat_holds_group_key'), 'seat_holds', ['group_key'], unique=False)
    op.create_table('refunds',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('booking_item_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('REFUND', 'TRAVEL_CREDIT', name='refund_type_enum', create_constraint=True), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.Enum('PENDING_APPROVAL', 'PROCESSED', 'EXPIRED', 'REJECTED', name='refund_status_enum', create_constraint=True), nullable=False),
    sa.Column('requires_approval', sa.Boolean(), nullable=False),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount > 0', name='ck_refund_amount_positive'),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['booking_item_id'], ['booking_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_refund_booking_item', 'refunds', ['booking_item_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_refund_booking_item', table_name='refunds')
    op.drop_table('refunds')
    op.drop_index(op.f('ix_seat_holds_group_key'), table_name='seat_holds')
    op.drop_table('seat_holds')
    op.drop_table('booking_items')
    op.drop_index('ix_waitlist_flight_class_status', table_name='waitlist_entries')
    op.drop_table('waitlist_entries')
    op.drop_index('ix_fare_seat_class_fare_type', table_name='fares')
    op.drop_table('fares')
    op.drop_index('ix_seat_class_flight_cabin', table_name='seat_classes')
    op.drop_table('seat_classes')
    op.drop_index(op.f('ix_flights_flight_number'), table_name='flights')
    op.drop_index('ix_flight_unique_per_day', table_name='flights')
    op.drop_table('flights')
    op.drop_index(op.f('ix_bookings_booking_reference'), table_name='bookings')
    op.drop_table('bookings')
    op.drop_index('ix_audit_entity', table_name='audit_logs')
    op.drop_index('ix_audit_actor_created', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
